### ISSUE TITLE
Error occurs when blockOutStatusBar = true for iOS native app.

### ISSUE THREAD

**Issue by WasiqB** [wswebcreation/wdio-native-app-compare#13]
**Environment (please complete the following information):**
 - Node.js version: 13.6.0
 - NPM version: 6.13.6
 - webdriver.io version: 5.18.5
 - wdio-native-app-compare version: 1.1.0

**Config of webdriver.io and the plugin**

```javascript
nativeAppCompare: {
  baselineFolder: join(process.cwd(), './snapshots/baselines'),
  screenshotPath: join(process.cwd(), 'snapshots/'),
  autoSaveBaseline: true,
  blockOutStatusBar: true,
  blockOutIphoneXBottomBar: true,
  blockOutNavigationBar: true,
  imageNameFormat: '{tag}-{platformName}-{deviceName}'
}
```

**Describe the bug**

When `blockOutStatusBar` is `true`, I get following Error,

```bash
[iPhone 8 Plus MAC 13.3 #0-0] Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/in-wasiq.bhamla/Documents/my-git/my-wdio/test/mobile/mobile.spec.js)
[iPhone 8 Plus MAC 13.3 #0-0]     at Hook.Runnable._timeoutError (/Users/in-wasiq.bhamla/Documents/my-git/my-wdio/node_modules/@wdio/mocha-framework/node_modules/mocha/lib/runnable.js:455:10)
[iPhone 8 Plus MAC 13.3 #0-0]     at Timeout.<anonymous> (/Users/in-wasiq.bhamla/Documents/my-git/my-wdio/node_modules/@wdio/mocha-framework/node_modules/mocha/lib/runnable.js:266:24)
[iPhone 8 Plus MAC 13.3 #0-0]     at listOnTimeout (internal/timers.js:549:17)
[iPhone 8 Plus MAC 13.3 #0-0]     at processTimers (internal/timers.js:492:7)
```

**To Reproduce**
Steps to reproduce the behaviour: Check my repo [here](https://github.com/WasiqB/my-wdio).

You only need to change `blockOutStatusBar` to `true` in config `conf/mobile/wdio.ios.conf.js` and run `npm run ios`.

**Expected behaviour**

It is expected that the screens top status bar should be blocked out as currently being done for Android.

**Screenshots**

Following is the screenshot when the above mentioned flag is set to `false`.

![homescreen-ios-iphone_8_plus](https://user-images.githubusercontent.com/9130909/72884171-afc47f80-3d2b-11ea-954d-6fd43b9e8feb.png)

**Additional context**

Check Appium logs [here](https://gist.github.com/WasiqB/851b9e5e2309d58fff6f970432ca1283).

**Comment by wswebcreation** [comment]
Thanks for filing an issue, it looks like the header is not detected. as an element. I'll try to debug it the coming days and let you know

**Comment by wswebcreation** [comment]
@WasiqB 

After debugging this for 2 hours I found out that this is not an issue with the module, but with your project.  You messed up your timeouts. Take for example this `browser.setTimeout({ 'implicit': 60000 });`. This is the time in milliseconds to retry the element location strategy when Appium can't find the element. If you look at your your framework options you set the timeout to this

```js
    mochaOpts: {
        ui: 'tdd',
        compilers: ['js:@babel/register'],
        timeout: 60000
    },
```

This will conflict if an element can't be found and kill the session. You also have this in your project 

```js
const waitforTimeout = 30 * 60000;
const commandTimeout = 30 * 60000;
```

This will exceed the 60 seconds you have in your framework and will never work.

If you for example set this `browser.setTimeout({ 'implicit': 30000 });`  then it will work.

Some technical details about the module, it tries to automatically find the status bar element and determine the rectangles. If it can't find it, then it will fall back to a default. Because iOS 13 doesn't return the statusbar element anymore, it will not find the element. But with your implicit wait of 60 seconds and the framework timeout it will break. So if you set the timeouts correct it will work.

I'll close this issue for now.

**Comment by WasiqB** [comment]
@wswebcreation , after making suggested changes, now the test is executing without errors.

Just one thought though, if iOS 13 does not return status bar anymore, then ideally it should not be found in the first place. Since in the logs, I can see this,

```bash
2020-01-26T10:43:54.630Z INFO webdriver: [POST] http://127.0.0.1:4723/wd/hub/session/f16a77df-d396-4663-b948-c4031fb118e8/element
2020-01-26T10:43:54.630Z INFO webdriver: DATA { using: 'xpath', value: '//XCUIElementTypeStatusBar' }
[0-0] 2020-01-26T10:44:24.702Z INFO webdriver: RESULT {
  error: 'no such element',
  message: 'An element could not be located on the page using the given search parameters.',
  stacktrace: 'NoSuchElementError: An element could not be located on the page using the given search parameters.\n' +
    '    at XCUITestDriver.doNativeFind (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/find.js:126:11)'
}
[0-0] 2020-01-26T10:44:24.708Z WARN wdio-native-app-compare-service: The statusbar could not be determined and has been set to the defaults!
```

Can this be handled, if the platform is iOS >= 13, then status bar find can be ignored completely. Any thoughts on this?

**Comment by wswebcreation** [comment]
Hi @WasiqB 

I understand what you're saying but I can't determine the platform version in the module. And it could be that in a new release of Appium we get it back again so I want to be backwards compatible
